### ISSUE TITLE
Problem installing: Could not determine java version from '11.0.8'

### ISSUE THREAD

**Issue by armpakornia** [ppazos/cabolabs-ehrserver#1089]
I have a problem installing EHRServer on my machine.
After install prerequisites (JDK 11.0.8, MySQL, Grails), I run `grails run-app`. Grails shows this message: `Error initializing classpath: Could not determine java version from '11.0.8'.`

Here is the stacktrace:
`
 Error Error initializing classpath: Could not determine java version from '11.0.8'. (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.IllegalArgumentException: Could not determine java version from '11.0.8'.
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
	at org.gradle.api.JavaVersion.current(JavaVersion.java:80)
	at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
	at org.gradle.tooling.internal.provider.DefaultConnection.configure(DefaultConnection.java:88)
	at org.gradle.tooling.internal.consumer.connection.AbstractPost12ConsumerConnection.configure(AbstractPost12ConsumerConnection.java:37)
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.createConnection(DefaultToolingImplementationLoader.java:100)
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:88)
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:44)
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:43)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
| Error Error initializing classpath: Could not determine java version from '11.0.8'.
`
OS: Ubuntu 20.04 LTS
Java: 
`openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
`
Grails :
`
| Grails Version: 4.0.4
| JVM Version: 11.0.8
`

Please help me fixing this problem. Thank you.

**Comment by ppazos** [comment]
@armpakornia java 11 is not supported, please read the guide: https://cloudehrserver.com/learn

Also check https://stackoverflow.com/questions/51867798/does-grails-3-x-support-java-11
