### ISSUE TITLE
Add test for commit of new version for acompo thar already has a.new version

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#229]
Commit v1,
Checkout v1
Checkout v1 again
Commit new version v1 (will create v2)
Commit new version v1 (should fail because of concurrent edition, and should checkout latest version to commit a new one becauae we only support lineal versioning)

**Comment by ppazos** [comment]
The second commit doesn't check if the version that is updated is the latest version, and tries to save the XML on the filesystem but fails because the file already exists.

**Comment by ppazos** [comment]
We have a problem because the new Version is saved before verifying the versioning. To verify the versioning the latesVersion method is needed, but it expects the database to be in an stable state with just one version as latest, and we have 2. Because the commit is transactional, the changes are rolled back and the database has just one latest version for the compo.

Fails in the .get
```
   Version getLatestVersion()
   {
      def c = Version.createCriteria()
      def v = c.get {
         like('uid', this.uid + '::%')
         data {
            eq('lastVersion', true)
         }
      }
      return v
   }
```

Exception
```
org.hibernate.NonUniqueResultException: query did not return a unique result: 2
	at org.hibernate.internal.AbstractQueryImpl.uniqueElement(AbstractQueryImpl.java:975)
	at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:402)
	at grails.orm.HibernateCriteriaBuilder.executeUniqueResultWithProxyUnwrap(HibernateCriteriaBuilder.java:144)
	at org.codehaus.groovy.grails.orm.hibernate.query.AbstractHibernateCriteriaBuilder.invokeMethod(AbstractHibernateCriteriaBuilder.java:1643)
	at org.codehaus.groovy.grails.orm.hibernate.query.AbstractHibernateCriteriaBuilder.get(AbstractHibernateCriteriaBuilder.java:1525)
	at org.grails.datastore.mapping.query.api.BuildableCriteria$get.call(Unknown Source)
	at common.change_control.VersionedComposition.getLatestVersion(VersionedComposition.groovy:50)
```

**Comment by ppazos** [comment]
Done!
