### ISSUE TITLE
Check commit issue on last deployment from committer

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#300]
```
==> app-root/logs/jbossews.log <==
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
2016-02-28 17:01:58,848 [http-bio-127.11.43.129-8080-exec-8] ERROR validation.DeferredBindingActions  - Error running deferred data binding: Cann
ot invoke method instanceOf() on null object
java.lang.NullPointerException: Cannot invoke method instanceOf() on null object
        at com.cabolabs.ehrserver.openehr.common.change_control.Contribution.equals(Contribution.groovy:63)
        at java.util.ArrayList.indexOf(ArrayList.java:298)
        at java.util.ArrayList.contains(ArrayList.java:281)
        at grails.validation.DeferredBindingActions.runActions(DeferredBindingActions.java:65)
        at com.cabolabs.ehrserver.parsers.XmlService$_manageVersionedCompositions_closure4.doCall(XmlService.groovy:177)
        at com.cabolabs.ehrserver.parsers.XmlService.manageVersionedCompositions(XmlService.groovy:160)
        at com.cabolabs.ehrserver.parsers.XmlService.processCommit(XmlService.groovy:70)
        at com.cabolabs.ehrserver.api.RestController.commit(RestController.groovy:301)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
        at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
2016-02-28 17:01:58,880 [http-bio-127.11.43.129-8080-exec-8] ERROR spi.SqlExceptionHelper  - Column 'ehr_id' cannot be null
2016-02-28 17:01:58,884 [http-bio-127.11.43.129-8080-exec-8] ERROR api.RestController  - Hibernate operation: could not execute statement; SQL [n
/a]; Column 'ehr_id' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'ehr_
id' cannot be null DataIntegrityViolationException
Hibernate operation: could not execute statement; SQL [n/a]; Column 'ehr_id' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.
MySQLIntegrityConstraintViolationException: Column 'ehr_id' cannot be null DataIntegrityViolationException
```

**Comment by ppazos** [comment]
done
