### ISSUE TITLE
When the reset password link is clicked after the password was already reset, there is an exception.

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#311]
1. Create a user
2. Reset password
3. Go to the email again, and click on the reset password link
4. 
```
2016-03-07 10:07:02,201 [http-bio-127.11.43.129-8080-exec-7] WARN  servlet.DefaultGrailsApplicationAttributes  - No bean named [groovyPagesTempla
teEngine] defined in Spring application context!
2016-03-07 10:12:44,256 [http-bio-127.11.43.129-8080-exec-6] ERROR errors.GrailsExceptionResolver  - PowerAssertionError occurred when processing
 request: [POST] /ehr/user/resetPassword
assert user
       |
       null. Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [resetPassword] of controller [com.cabolabs.
security.UserController]  caused exception: Runtime error executing action
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
        ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
        ... 8 more
Caused by: Assertion failed:
assert user
       |
       null
        at com.cabolabs.security.UserController.$tt__resetPassword(UserController.groovy:461)
        ... 8 more
```

**Comment by ppazos** [comment]
Done.
