### ISSUE TITLE
mail tests fail in travis because missing email configuration

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#582]
| Failure:  sendUserRegisteredEmail(com.cabolabs.notification.NotificationServiceIntegrationSpec)
|  java.lang.IllegalArgumentException: from cannot be null or 0 length
	at grails.plugin.mail.MailMessageBuilder.from(MailMessageBuilder.groovy:227)
	at com.cabolabs.notification.NotificationService._tt__sendMail_closure6(NotificationService.groovy:114)
	at grails.plugin.mail.MailService.sendMail(MailService.groovy:53)
	at grails.plugin.mail.MailService.sendMail(MailService.groovy:59)
	at com.cabolabs.notification.NotificationService.$tt__sendMail(NotificationService.groovy:113)
	at com.cabolabs.notification.NotificationService.$tt__sendUserRegisteredEmail(NotificationService.groovy:50)
	at com.cabolabs.notification.NotificationServiceIntegrationSpec.sendUserRegisteredEmail(NotificationServiceIntegrationSpec.groovy:24)
| Running 10 integration tests... 31 of 31
--Output from sendUserCreatedEmail--
| Failure:  sendUserCreatedEmail(com.cabolabs.notification.NotificationServiceIntegrationSpec)
|  java.lang.IllegalArgumentException: from cannot be null or 0 length
	at grails.plugin.mail.MailMessageBuilder.from(MailMessageBuilder.groovy:227)
	at com.cabolabs.notification.NotificationService._tt__sendMail_closure6(NotificationService.groovy:114)
	at grails.plugin.mail.MailService.sendMail(MailService.groovy:53)
	at grails.plugin.mail.MailService.sendMail(MailService.groovy:59)
	at com.cabolabs.notification.NotificationService.$tt__sendMail(NotificationService.groovy:113)
	at com.cabolabs.notification.NotificationService.$tt__sendUserCreatedEmail(NotificationService.groovy:87)
	at com.cabolabs.notification.NotificationServiceIntegrationSpec.sendUserCreatedEmail(NotificationServiceIntegrationSpec.groovy:45)
| Failure:  sendUserCreatedEmail(com.cabolabs.notification.NotificationServiceIntegrationSpec)
|  java.lang.IllegalArgumentException: from cannot be null or 0 length
	at grails.plugin.mail.MailMessageBuilder.from(MailMessageBuilder.groovy:227)
	at com.cabolabs.notification.NotificationService._tt__sendMail_closure6(NotificationService.groovy:114)
	at grails.plugin.mail.MailService.sendMail(MailService.groovy:53)
	at grails.plugin.mail.MailService.sendMail(MailService.groovy:59)
	at com.cabolabs.notification.NotificationService.$tt__sendMail(NotificationService.groovy:113)
	at com.cabolabs.notification.NotificationService.$tt__sendUserCreatedEmail(NotificationService.groovy:87)
	at com.cabolabs.notification.NotificationServiceIntegrationSpec.sendUserCreatedEmail(NotificationServiceIntegrationSpec.groovy:45)
| Running 10 integration tests... 32 of 32
--Output from sendForgotPasswordEmail--
| Failure:  sendForgotPasswordEmail(com.cabolabs.notification.NotificationServiceIntegrationSpec)
|  java.lang.IllegalArgumentException: from cannot be null or 0 length
	at grails.plugin.mail.MailMessageBuilder.from(MailMessageBuilder.groovy:227)
	at com.cabolabs.notification.NotificationService._tt__sendMail_closure6(NotificationService.groovy:114)
	at grails.plugin.mail.MailService.sendMail(MailService.groovy:53)
	at grails.plugin.mail.MailService.sendMail(MailService.groovy:59)
	at com.cabolabs.notification.NotificationService.$tt__sendMail(NotificationService.groovy:113)
	at com.cabolabs.notification.NotificationService.$tt__sendForgotPasswordEmail(NotificationService.groovy:108)
	at com.cabolabs.notification.NotificationServiceIntegrationSpec.sendForgotPasswordEmail(NotificationServiceIntegrationSpec.groovy:66)
| Failure:  sendForgotPasswordEmail(com.cabolabs.notification.NotificationServiceIntegrationSpec)
|  java.lang.IllegalArgumentException: from cannot be null or 0 length
	at grails.plugin.mail.MailMessageBuilder.from(MailMessageBuilder.groovy:227)
	at com.cabolabs.notification.NotificationService._tt__sendMail_closure6(NotificationService.groovy:114)
	at grails.plugin.mail.MailService.sendMail(MailService.groovy:53)
	at grails.plugin.mail.MailService.sendMail(MailService.groovy:59)
	at com.cabolabs.notification.NotificationService.$tt__sendMail(NotificationService.groovy:113)
	at com.cabolabs.notification.NotificationService.$tt__sendForgotPasswordEmail(NotificationService.groovy:108)
	at com.cabolabs.notification.NotificationServiceIntegrationSpec.sendForgotPasswordEmail(NotificationServiceIntegrationSpec.groovy:66)

**Comment by ppazos** [comment]
this was solved
