### ISSUE TITLE
API commit exception if format is empty

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#630]
```
Cannot invoke method call() on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot invoke method call() on null object
        at com.cabolabs.ehrserver.api.RestController$_renderError_closure2$_closure31$_closure32.doCall(RestController.groovy:253)
        at com.cabolabs.ehrserver.api.RestController$_renderError_closure2$_closure31.doCall(RestController.groovy:252)
        at com.cabolabs.ehrserver.api.RestController.renderError(RestController.groovy:219)
        at com.cabolabs.ehrserver.api.RestController.commit(RestController.groovy:502)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
        at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by ppazos** [comment]
Fixed with #629
